//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTiecCuoi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDichVu
    {
        public string MaDV { get; set; }
        public string TenDV { get; set; }
        public string SoLuong { get; set; }
        public Nullable<int> GiaDV { get; set; }
        public string MaTiecCuoi { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual TiecCuoi TiecCuoi { get; set; }
    }
}
