//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTiecCuoi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTMonAn
    {
        public string MaMonAn { get; set; }
        public string MaTiecCuoi { get; set; }
        public string TenMonAn { get; set; }
        public Nullable<int> GiaMonAn { get; set; }
        public string GhiChi { get; set; }
    
        public virtual MonAn MonAn { get; set; }
        public virtual TiecCuoi TiecCuoi { get; set; }
    }
}
