//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTiecCuoi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LoaiSanh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiSanh()
        {
            this.Sanhs = new HashSet<Sanh>();
        }
        public int MaLoaiSanh { get; set; }
        [StringLength(30)]
        [Required(ErrorMessage ="Vui lòng nhập tên sảnh")]
        public string TenLoaiSanh { get; set; }
        [Required(ErrorMessage ="Vui lòng nhập giá bàn tối thiểu")]
        [Range(1000000,100000000,ErrorMessage ="Đơn giá bàn tối thiểu phải lớn hơn 1 triệu và nhỏ hơn 100 triệu")]
        public Nullable<int> GiaBanToiThieu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sanh> Sanhs { get; set; }
    }
}
