//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTiecCuoi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLyTiecCuoiEntities : DbContext
    {
        public QLyTiecCuoiEntities()
            : base("name=QLyTiecCuoiEntities")
        {
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTDichVu> CTDichVus { get; set; }
        public virtual DbSet<CTMonAn> CTMonAns { get; set; }
        public virtual DbSet<DichVu> DichVus { get; set; }
        public virtual DbSet<DoanhSo> DoanhSoes { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<LoaiSanh> LoaiSanhs { get; set; }
        public virtual DbSet<MonAn> MonAns { get; set; }
        public virtual DbSet<Sanh> Sanhs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TiecCuoi> TiecCuois { get; set; }
    }
}
