//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTiecCuoi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiecCuoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TiecCuoi()
        {
            this.CTDichVus = new HashSet<CTDichVu>();
            this.CTMonAns = new HashSet<CTMonAn>();
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public string MaTiecCuoi { get; set; }
        public string TenChuRe { get; set; }
        public string TenCoDau { get; set; }
        public string SoDienThoai { get; set; }
        public Nullable<System.DateTime> NgayCuoi { get; set; }
        public string MaSanh { get; set; }
        public string SoBan { get; set; }
        public string SoBanDuTru { get; set; }
        public Nullable<int> TienCoc { get; set; }
        public string MaCa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDichVu> CTDichVus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTMonAn> CTMonAns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual Sanh Sanh { get; set; }
        public virtual LoaiCa LoaiCa { get; set; }
    }
}
